#ifndef _ALPHABET_H_
#define _ALPHABET_H_
#define RECHT 0
#define SENSITIVITY_OVERDRACHT 1
#define NEXT_PERIOD 2
#define KROM 3
#define ONTVANG_SENSOR_DATA 4
#define RIJ_VOORUIT 5
#define RANGE 6
#define SNEL 7
#define LANGZAAM 8
#define LOSKOPPEL 9
#define RIJ_ACHTERUIT 10
#define VERZOEK_SENSOR_DATA 11
#define BEPAAL_ALGO_ACTIE 12
#define AANKOPPEL 13
#define SYSTEEM_ACTIE_OVERDRACHT 14
#define ONTVANG_ACTIE 15
#define STOP 16
#define BEPAAL_ACTIE 17
#define STUUR_SENSITIVITY 18
#define HOOG_LAAG 19
#define STUUR_ACTIE 20

#define ONTVANG_SENSITIVITY 22
#endif /*_ALPHABET_H_*/
