#define DEBUG_LOCO      0
#define DEBUG_ONTKOPPEL 0
#define DEBUG_WISSEL    0
#define DEBUG_SENSOR    0
#define DEBUG_SYNC      0
#define DEBUG_INIT      0
#define DEBUG_HDS_SENSOR 0
#define DEBUG_TREINBAAN 0
#define DEBUG_RANGEER 0
